### FASE 1. Carga e integración de datos

**Proyecto:** Análisis Exploratorio de Datos — Ingresos totales por ventas a clientes de un comercio.

**Objetivo de esta fase:**
Importar los datos desde las distintas fuentes disponibles y preparar un único dataset consolidado sobre el que trabajar en las siguientes fases (limpieza, EDA e informe).

**Fuentes de datos:**
- `clientes.csv` → información de los clientes  (edad, estado civil, ingresos, ciudad, , etc.)
- `ventas.xlsx` → 5 hojas: 1 hoja con los productos y la información de las ventas, repartidas en 4 hojas (2022, 2023, 2025, 2025)

### 1️⃣ Importar librerías

In [2]:
import pandas as pd
import numpy as np

# Para que se muestren todas las columnas al inspeccionar los DataFrames
pd.set_option('display.max_columns', None)

### 2️⃣ Cargar `clientes.csv`
Este archivo contiene la informacion de los clientes.

In [4]:
df_clientes = pd.read_csv(r"../data/raw/clientes.csv")

#### Comprobación de la carga

In [5]:
# Primeras 5 filas
df_clientes.head()

,Unnamed: 0,id_,edad,estado_civil,nivel_educativo,ingresos_anuales,tiene_hijos,adolescentes_en_casa,fecha_registro,ciudad,region,latitude,longitude,segmento_cliente,visitas_web_mes
0,0,b9e805ce-fe13-4ed5-82b1-286271529391,44.0,casado,grado universitario,30544,1.0,0.0,20-octubre-2021,Barcelona,Este,39.838,-7.047,Recurrente,9
1,1,fa2c965b-9356-48b4-84f1-ee1bf213cee9,26.0,casado,bachillerato,46779,0.0,0.0,21-agosto-2019,Malaga,Sur,39.741,0.201,VIP,4
2,2,0dd76b11-d81d-4df7-8ef0-23dab7ccf86f,50.0,Casado,master,22003,1.0,0.0,3-diciembre-2020,Vigo,Norte,38.971,-6.919,Nuevo,8
3,3,ac5ab989-4b81-4b83-8b09-5842b10bacc4,52.0,casado,grado universitario,41512,0.0,0.0,29-diciembre-2021,Malaga,Sur,36.810,1.782,Nuevo,8
4,4,11f866be-75b7-40d2-a32f-2161caf21791,18.0,Casado,bachillerato,45029,0.0,0.0,4-septiembre-2021,Valencia,Este,39.879,-0.514,Corporativo,4

In [9]:
#  Dimensiones del dataset
print("(Filas , Columnas):",df_clientes.shape)

(Filas , Columnas): (8000, 15)

In [18]:
# Nombres de las columnas
print("El archivo df_clientes esta compuesto por las columnas:\n",df_clientes.columns)

El archivo df_clientes esta compuesto por las columnas:
 Index(['Unnamed: 0', 'id_', 'edad', 'estado_civil', 'nivel_educativo',
       'ingresos_anuales', 'tiene_hijos', 'adolescentes_en_casa',
       'fecha_registro', 'ciudad', 'region', 'latitude', 'longitude',
       'segmento_cliente', 'visitas_web_mes'],
      dtype='str')

In [19]:
# Tipos de datos y nulos por columnas
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            8000 non-null   int64
 1   id_                   8000 non-null   str
 2   edad                  7520 non-null   float64
 3   estado_civil          7920 non-null   str
 4   nivel_educativo       7680 non-null   str
 5   ingresos_anuales      8000 non-null   int64
 6   tiene_hijos           7840 non-null   float64
 7   adolescentes_en_casa  8000 non-null   float64
 8   fecha_registro        7960 non-null   str
 9   ciudad                8000 non-null   str
 10  region                8000 non-null   str
 11  latitude              8000 non-null   float64
 12  longitude             8000 non-null   float64
 13  segmento_cliente      8000 non-null   str
 14  visitas_web_mes       8000 non-null   int64
dtypes: float64(5), int64(3), str(7)
memory usage: 1.6 MB

**Observaciones iniciales:**
- Aparece una columna `Unnamed: 0` que es un índice residual del archivo original y no aporta información → se eliminará.
- La columna `fecha_registro` se han cargado como texto (`str`). Esto se corregirá en la **Fase 2 (Limpieza)**.
- Hay columnas con valores nulos (`edad`, `estado_civil`, `nivel_educativo`, `tiene_hijos`, `fecha_registro`),se tratarán en la **Fase 2 (Limpieza)**.
- Las columnas (`tiene_hijos`, `adolescentes_en_casa`) en una primera visual parecen variables binarias, se tratarán en la **Fase 2 (Limpieza)**.

#### 3️⃣ Cargar `ventas.csv`

Este archivo contiene 5 hojas, la HOJA 1 con los productos dispoblibles en tienda, y las HOJAS 2 A 5 con las ventas realizadas en los años (2022, 2023, 2024, 2025).

In [20]:
# Comprobamos las hojas que tiene el Excel
excel_ventas = pd.ExcelFile(r"../data/raw/ventas.xlsx")
print("El excel ventas lo compone las Hojas:\n",excel_ventas.sheet_names)

El excel ventas lo compone las Hojas:
 ['productos', '2022', '2023', '2024', '2025']

#### **Hoja Productos**

In [21]:
# Cargamos la hoja productos
df_productos = pd.read_excel(excel_ventas, sheet_name="productos")

In [22]:
# Primeras 5 filas
df_productos.head()

,Unnamed: 0,product_id,categoria_producto,nombre_producto,marca,costo_unitario,precio_lista,peso_kg,proveedor,stock_disponible,fecha_lanzamiento,rating_promedio_producto
0,0,P0001,Electronica,Auriculares Urbanix Basic,Urbanix,"26,73","45,70",9.60,Global Supply SL,383,31-mayo-2020,3.60
1,1,P0002,Electronica,Auriculares Urbanix Pro,Urbanix,"47,97","77,93",11.86,Global Supply SL,392,8-marzo-2019,3.29
2,2,P0003,Electronica,Auriculares Nova Max,Nova,"49,49","98,89",8.54,Global Supply SL,317,16-junio-2023,4.18
3,3,P0004,Electronica,Smartphone Norte&Co Basic,Norte&Co,"60,57","95,49",3.60,Comercial Atlas,303,23-enero-2019,2.94
4,4,P0005,Electronica,Smartphone Zentra Pro,Zentra,"17,49","26,00",1.69,Norte Logistica,387,30-enero-2021,3.95

In [24]:
#  Dimensiones del dataset
print("(Filas , Columnas):",df_productos.shape)

(Filas , Columnas): (90, 12)

In [25]:
# Nombres de las columnas
print("El archivo df_clientes esta compuesto por las columnas:\n",df_productos.columns)

El archivo df_clientes esta compuesto por las columnas:
 Index(['Unnamed: 0', 'product_id', 'categoria_producto', 'nombre_producto',
       'marca', 'costo_unitario', 'precio_lista', 'peso_kg', 'proveedor',
       'stock_disponible', 'fecha_lanzamiento', 'rating_promedio_producto'],
      dtype='str')

In [26]:
# Tipos de datos y nulos por columnas
df_productos.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                90 non-null     int64
 1   product_id                90 non-null     str
 2   categoria_producto        90 non-null     str
 3   nombre_producto           90 non-null     str
 4   marca                     89 non-null     str
 5   costo_unitario            90 non-null     str
 6   precio_lista              90 non-null     str
 7   peso_kg                   90 non-null     float64
 8   proveedor                 90 non-null     str
 9   stock_disponible          90 non-null     int64
 10  fecha_lanzamiento         90 non-null     str
 11  rating_promedio_producto  88 non-null     float64
dtypes: float64(2), int64(2), str(8)
memory usage: 15.4 KB

**Observaciones iniciales de `df_productos`:**
- Aparece una columna `Unnamed: 0` que es un índice residual del archivo original y no aporta información → se eliminará.
- La columna `fecha_lanzamiento` se ha cargado como texto (`str`).Se corregirá en la **Fase 2 (Limpieza)**.
- Hay dos columna con valores nulos (`rating_promedio_producto`, `marca`),se tratarán en la **Fase 2 (Limpieza)**.
- Las columnas (`costo_unitario`, `precio_lista`) se cargaron como texto (`str`), se tratarán en la **Fase 2 (Limpieza)**.
- Se observa que la `columna product_id` esta relacionada con las Hojas 2022, 2023, 2024 ,2025, se comprobara antes de unirlas.

#### **Hojas 2022, 2023, 2024 ,2025**

In [27]:
# Cargamos cada hoja por separado
df_2022 = pd.read_excel(excel_ventas,sheet_name="2022")
df_2023 = pd.read_excel(excel_ventas,sheet_name="2023")
df_2024 = pd.read_excel(excel_ventas,sheet_name="2024")
df_2025 = pd.read_excel(excel_ventas,sheet_name="2025")

In [33]:
#  Dimensiones del dataset
for año, df in [("2022", df_2022), ("2023", df_2023), ("2024", df_2024), ("2025", df_2025)]:
    print(f"Año {año}: tiene {df.shape[0]} Filas y {df.shape[1]} Columnas ")

Año 2022: tiene 13000 Filas y 14 Columnas
Año 2023: tiene 13000 Filas y 14 Columnas
Año 2024: tiene 13000 Filas y 14 Columnas
Año 2025: tiene 13000 Filas y 14 Columnas

In [34]:
# Nombres de las columnas
for año, df in [("2022", df_2022), ("2023", df_2023), ("2024", df_2024), ("2025", df_2025)]:
    print(f"Columnas de {año}: {df.columns.tolist()}")

Columnas de 2022: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal']
Columnas de 2023: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal']
Columnas de 2024: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal']
Columnas de 2025: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal']

In [37]:
df_2022.sample(3)

,Unnamed: 0,order_id,id_,product_id,fecha_pedido,cantidad,precio_unitario,descuento,importe_total,metodo_pago,envio_gratis,calificacion,devuelto,canal
1425,1425,1426,e8027b11-018e-4f6b-882e-d848b3577d60,P0076,25-agosto-2022,2,"46,72",0.0,"93,45",Tarjeta de credito,1,NaN,NO,Tienda fisica
11863,11863,11864,af399746-bc6f-41c7-b007-b0c6739b5e7f,P0035,3-octubre-2022,1,"12,68",0.0,"12,68",Tarjeta de debito,1,NaN,no,Web
4445,4445,4446,bebe93e0-f766-4049-9adb-4a86dc7e3ff3,P0058,15-mayo-2022,5,"22,08",0.0,"110,40",tarjeta de credito,0,4.0,NO,Web

In [36]:
df_2023.sample(3)

,Unnamed: 0,order_id,id_,product_id,fecha_pedido,cantidad,precio_unitario,descuento,importe_total,metodo_pago,envio_gratis,calificacion,devuelto,canal
7889,7889,20890,5257afd3-bfbf-40e4-9bd6-f3b706ef4b7e,P0037,12-octubre-2023,2,"109,86",0.20,"175,78",PAYPAL,0,4.0,NO,Web
12135,12135,25136,29de58a0-a142-4a9a-9f5a-ab4949943f21,P0020,28-mayo-2023,1,"63,50",0.10,"57,15",NaN,0,5.0,no,Tienda fisica
8916,8916,21917,9d16964f-e3b9-4195-bf33-bd89ae38cde9,P0027,27-mayo-2023,2,"102,59",0.15,"174,40",PAYPAL,0,4.0,no,App movil

In [38]:
df_2024.sample(3)

,Unnamed: 0,order_id,id_,product_id,fecha_pedido,cantidad,precio_unitario,descuento,importe_total,metodo_pago,envio_gratis,calificacion,devuelto,canal
2942,2942,28943,898f04ee-fd11-4f4a-978c-9977a9a6276a,P0032,10-septiembre-2024,2,"11,01",0.20,"17,61",Tarjeta de credito,0,5.0,NO,Web
12770,12770,38771,73d62d1d-a7dc-4c0f-851a-d36e09bd8388,P0073,2-mayo-2024,2,"47,50",0.15,"80,75",Transferencia,0,5.0,NO,Web
7789,7789,33790,d1ba7079-59ec-4d31-ad86-8ddb3f54cb30,P0072,5-octubre-2024,2,"101,83",0.10,"183,29",TARJETA DE CREDITO,1,5.0,no,App movil

In [39]:
df_2025.sample(3)

,Unnamed: 0,order_id,id_,product_id,fecha_pedido,cantidad,precio_unitario,descuento,importe_total,metodo_pago,envio_gratis,calificacion,devuelto,canal
3502,3502,42503,055e13be-a086-4470-b38d-22f6ff0632c9,P0014,27-enero-2025,1,"37,76",0.05,"35,87",TARJETA DE CREDITO,1,4.0,no,Tienda fisica
9707,9707,48708,50b35a94-9317-4eed-9b06-19cccb2168e3,P0084,1-septiembre-2025,3,"45,68",0.10,"123,34",Tarjeta de debito,0,2.0,no,Web
8154,8154,47155,69bf8f2c-a521-417f-a47c-2978c1953cdc,P0079,12-abril-2025,1,"51,70",0.20,"41,36",Tarjeta de debito,0,NaN,NO,Web

In [42]:
df_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       13000 non-null  int64
 1   order_id         13000 non-null  int64
 2   id_              13000 non-null  str
 3   product_id       13000 non-null  str
 4   fecha_pedido     13000 non-null  str
 5   cantidad         13000 non-null  int64
 6   precio_unitario  13000 non-null  str
 7   descuento        13000 non-null  float64
 8   importe_total    13000 non-null  str
 9   metodo_pago      12805 non-null  str
 10  envio_gratis     13000 non-null  int64
 11  calificacion     11125 non-null  float64
 12  devuelto         13000 non-null  str
 13  canal            13000 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 2.5 MB

In [43]:
df_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       13000 non-null  int64
 1   order_id         13000 non-null  int64
 2   id_              13000 non-null  str
 3   product_id       13000 non-null  str
 4   fecha_pedido     13000 non-null  str
 5   cantidad         13000 non-null  int64
 6   precio_unitario  13000 non-null  str
 7   descuento        13000 non-null  float64
 8   importe_total    13000 non-null  str
 9   metodo_pago      12805 non-null  str
 10  envio_gratis     13000 non-null  int64
 11  calificacion     11072 non-null  float64
 12  devuelto         13000 non-null  str
 13  canal            13000 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 2.5 MB

In [44]:
df_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       13000 non-null  int64
 1   order_id         13000 non-null  int64
 2   id_              13000 non-null  str
 3   product_id       13000 non-null  str
 4   fecha_pedido     13000 non-null  str
 5   cantidad         13000 non-null  int64
 6   precio_unitario  13000 non-null  str
 7   descuento        13000 non-null  float64
 8   importe_total    13000 non-null  str
 9   metodo_pago      12805 non-null  str
 10  envio_gratis     13000 non-null  int64
 11  calificacion     11053 non-null  float64
 12  devuelto         13000 non-null  str
 13  canal            13000 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 2.5 MB

In [45]:
df_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       13000 non-null  int64
 1   order_id         13000 non-null  int64
 2   id_              13000 non-null  str
 3   product_id       13000 non-null  str
 4   fecha_pedido     13000 non-null  str
 5   cantidad         13000 non-null  int64
 6   precio_unitario  13000 non-null  str
 7   descuento        13000 non-null  float64
 8   importe_total    13000 non-null  str
 9   metodo_pago      12805 non-null  str
 10  envio_gratis     13000 non-null  int64
 11  calificacion     10977 non-null  float64
 12  devuelto         13000 non-null  str
 13  canal            13000 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 2.5 MB

**Observaciones iniciales de `df_2022, df_2023, df_2024, df_2025`:**
- Aparece una columna `Unnamed: 0` que es un índice residual del archivo original y no aporta información → se eliminará.
- La columna `fecha_pedido` se ha cargado como texto (`str`).Se corregirá en la **Fase 2**.
- Hay dos columnas con valores nulos (`metodo_pago`,`calificacion` ),se tratarán en la **Fase 2**.
- Las columnas (`precio_unitario`, `importe_total`) se cargaron como texto (`str`), se tratarán en la **Fase 2**.
- La columna (`envio_gratis`) en una primera visual parece una variable binaria, se tratarán en la **Fase 2**.
- Se observa que la `columna product_id` esta relacionada con las Hojas 2022, 2023, 2024 ,2025, se comprobara antes de unirlas.

#### 4️⃣ Unir  `df_2022, df_2023, df_2024, df_2025` del archivo `ventas.csv`

Como las 4 hojas tienen exactamente las mismas columnas y representan el mismo tipo de información, las unimos verticalmente con pd.concat().

Antes de unirlas, añadimos una columna `hoja_origen` para no perder la trazabilidad de qué hoja proviene cada registro (nos sera útil más adelante).

In [46]:
# Añadimos una columna que identifique el año/hoja de origen antes de concatenar
df_2022["hoja_origen"] = "2022"
df_2023["hoja_origen"] = "2023"
df_2024["hoja_origen"] = "2024"
df_2025["hoja_origen"] = "2025"

In [47]:
# Verificamos que se ha añadido la columna "hoja_origen"
#  Dimensiones del dataset
for año, df in [("2022", df_2022), ("2023", df_2023), ("2024", df_2024), ("2025", df_2025)]:
    print(f"Año {año}: tiene {df.shape[0]} Filas y {df.shape[1]} Columnas ")

Año 2022: tiene 13000 Filas y 15 Columnas
Año 2023: tiene 13000 Filas y 15 Columnas
Año 2024: tiene 13000 Filas y 15 Columnas
Año 2025: tiene 13000 Filas y 15 Columnas

In [48]:
# Nombres de las columnas
for año, df in [("2022", df_2022), ("2023", df_2023), ("2024", df_2024), ("2025", df_2025)]:
    print(f"Columnas de {año}: {df.columns.tolist()}")

Columnas de 2022: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal', 'hoja_origen']
Columnas de 2023: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal', 'hoja_origen']
Columnas de 2024: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal', 'hoja_origen']
Columnas de 2025: ['Unnamed: 0', 'order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad', 'precio_unitario', 'descuento', 'importe_total', 'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal', 'hoja_origen']

#### Concatenamos

In [49]:
df_ventas = pd.concat([df_2022, df_2023, df_2024,df_2025], ignore_index=True)

In [50]:
df_ventas.sample(5)

,Unnamed: 0,order_id,id_,product_id,fecha_pedido,cantidad,precio_unitario,descuento,importe_total,metodo_pago,envio_gratis,calificacion,devuelto,canal,hoja_origen
1724,1724,1725,9bca00ee-70f8-4897-bf27-7ea904078e0d,P0079,18-noviembre-2022,3,"77,81",0.10,"210,09",tarjeta de credito,0,NaN,NO,App movil,2022
38077,12077,38078,b0a9f8a3-77e1-477b-b742-f560f43cf758,P0034,11-abril-2024,5,"15,91",0.00,"79,53",TARJETA DE CREDITO,0,5.0,no,App movil,2024
20997,7997,20998,d377b34f-a190-4142-b88c-99cbde40a6f6,P0089,17-septiembre-2023,1,"20,24",0.15,"17,20",Transferencia,1,NaN,NO,Web,2023
49453,10453,49454,f48fa0ee-4471-4076-bebd-949d30186c64,P0029,17-febrero-2025,2,"80,05",0.05,"152,09",TARJETA DE CREDITO,1,4.0,no,App movil,2025
32953,6953,32954,eb0ae961-1198-4ff0-b173-ca4f1e9bb34f,P0020,30-octubre-2024,2,"13,68",0.00,"27,36",transferencia,1,NaN,no,Web,2024

#### Comprobación de la concatenación

In [52]:
# La suma de filas debe coincidir con la suma de las 3 hojas por separado
print("Filas 2022 + 2023 + 2024 + 2025:", len(df_2022) + len(df_2023) + len(df_2024) + len(df_2025))
print("Filas df_clientes:", len(df_ventas))

Filas 2022 + 2023 + 2024 + 2025: 52000
Filas df_clientes: 52000

In [51]:
#  Dimensiones del dataset
print("(Filas , Columnas):",df_ventas.shape)

(Filas , Columnas): (52000, 15)

In [53]:
# Reviamos el df_ventas 
df_ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       52000 non-null  int64
 1   order_id         52000 non-null  int64
 2   id_              52000 non-null  str
 3   product_id       52000 non-null  str
 4   fecha_pedido     52000 non-null  str
 5   cantidad         52000 non-null  int64
 6   precio_unitario  52000 non-null  str
 7   descuento        52000 non-null  float64
 8   importe_total    52000 non-null  str
 9   metodo_pago      51220 non-null  str
 10  envio_gratis     52000 non-null  int64
 11  calificacion     44227 non-null  float64
 12  devuelto         52000 non-null  str
 13  canal            52000 non-null  str
 14  hoja_origen      52000 non-null  str
dtypes: float64(2), int64(4), str(9)
memory usage: 10.6 MB

**Observaciones iniciales de `df_clientes`:**
- Aparece una columna `Unnamed: 0` que es un índice residual del archivo original y no aporta información → se eliminará.
- La columna `fecha_pedido` se ha cargado como texto (`str`).Se corregirá en la **Fase 2**.
- Hay dos columnas con valores nulos (`metodo_pago`,`calificacion` ),se tratarán en la **Fase 2**.
- Las columnas (`precio_unitario`, `importe_total`, `hoja_origen`) se cargaron como texto (`str`), se tratarán en la **Fase 2**.0
- La columna (`envio_gratis`) en una primera visual parece una variable binaria, se tratarán en la **Fase 2**.
- Se observa que la `columna product_id` esta relacionada con las Hojas 2022, 2023, 2024 ,2025, se comprobara antes de unirlas.

#### 5️⃣ Unir `df_ventas` con `df_productos`

Como hemos observado ambos comparten la columna `producto_id`, por lo que uniremos con `merge()` y con `how="left"` para conservar todas las dilas de `df_ventas`

In [56]:
# Comprobamos si hay algún product_id en df_ventas que no exista en df_productos
set(df_ventas["product_id"]) - set(df_productos["product_id"])

set()

In [57]:
df_ventas_productos = df_ventas.merge(df_productos, on="product_id", how="left")

In [58]:
print(len(df_ventas), len(df_ventas_productos))  # deberían ser iguales
df_ventas_productos.isnull().sum()  # si aparecen nulos en columnas de producto, algo no casó bien

52000 52000

Unnamed: 0_x                   0
order_id                       0
id_                            0
product_id                     0
fecha_pedido                   0
cantidad                       0
precio_unitario                0
descuento                      0
importe_total                  0
metodo_pago                  780
envio_gratis                   0
calificacion                7773
devuelto                       0
canal                          0
hoja_origen                    0
Unnamed: 0_y                   0
categoria_producto             0
nombre_producto                0
marca                        567
costo_unitario                 0
precio_lista                   0
peso_kg                        0
proveedor                      0
stock_disponible               0
fecha_lanzamiento              0
rating_promedio_producto    1133
dtype: int64

#### 6️⃣ Unimos df_ventas_productos con df_clientes

Como hemos observado ambos comparten la columna `id_`, por lo que uniremos con `merge()` y con `how="left"` para conservar todas las dilas de `df_ventas_productos`

In [59]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            8000 non-null   int64
 1   id_                   8000 non-null   str
 2   edad                  7520 non-null   float64
 3   estado_civil          7920 non-null   str
 4   nivel_educativo       7680 non-null   str
 5   ingresos_anuales      8000 non-null   int64
 6   tiene_hijos           7840 non-null   float64
 7   adolescentes_en_casa  8000 non-null   float64
 8   fecha_registro        7960 non-null   str
 9   ciudad                8000 non-null   str
 10  region                8000 non-null   str
 11  latitude              8000 non-null   float64
 12  longitude             8000 non-null   float64
 13  segmento_cliente      8000 non-null   str
 14  visitas_web_mes       8000 non-null   int64
dtypes: float64(5), int64(3), str(7)
memory usage: 1.6 MB

In [60]:
df_ventas_productos.info()

<class 'pandas.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0_x              52000 non-null  int64
 1   order_id                  52000 non-null  int64
 2   id_                       52000 non-null  str
 3   product_id                52000 non-null  str
 4   fecha_pedido              52000 non-null  str
 5   cantidad                  52000 non-null  int64
 6   precio_unitario           52000 non-null  str
 7   descuento                 52000 non-null  float64
 8   importe_total             52000 non-null  str
 9   metodo_pago               51220 non-null  str
 10  envio_gratis              52000 non-null  int64
 11  calificacion              44227 non-null  float64
 12  devuelto                  52000 non-null  str
 13  canal                     52000 non-null  str
 14  hoja_origen               52000 non-null  str
 15  Unnamed: 0_y              52000 non-null  int64
 16  categoria_producto        52000 non-null  str
 17  nombre_producto           52000 non-null  str
 18  marca                     51433 non-null  str
 19  costo_unitario            52000 non-null  str
 20  precio_lista              52000 non-null  str
 21  peso_kg                   52000 non-null  float64
 22  proveedor                 52000 non-null  str
 23  stock_disponible          52000 non-null  int64
 24  fecha_lanzamiento         52000 non-null  str
 25  rating_promedio_producto  50867 non-null  float64
dtypes: float64(4), int64(6), str(16)
memory usage: 18.6 MB

In [63]:
# Unir con df_clientes por la columna id_
df_final = df_ventas_productos.merge(df_clientes, on="id_", how="left")

In [65]:
df_final.columns

Index(['Unnamed: 0_x', 'order_id', 'id_', 'product_id', 'fecha_pedido',
       'cantidad', 'precio_unitario', 'descuento', 'importe_total',
       'metodo_pago', 'envio_gratis', 'calificacion', 'devuelto', 'canal',
       'hoja_origen', 'Unnamed: 0_y', 'categoria_producto', 'nombre_producto',
       'marca', 'costo_unitario', 'precio_lista', 'peso_kg', 'proveedor',
       'stock_disponible', 'fecha_lanzamiento', 'rating_promedio_producto',
       'Unnamed: 0', 'edad', 'estado_civil', 'nivel_educativo',
       'ingresos_anuales', 'tiene_hijos', 'adolescentes_en_casa',
       'fecha_registro', 'ciudad', 'region', 'latitude', 'longitude',
       'segmento_cliente', 'visitas_web_mes'],
      dtype='str')

In [66]:
# Eliminamos las columnas Unnamed
df_final= df_final.drop(columns=["Unnamed: 0_x", "Unnamed: 0_y","Unnamed: 0"])

In [71]:
# comprobamos 
df_final.columns

Index(['order_id', 'id_', 'product_id', 'fecha_pedido', 'cantidad',
       'precio_unitario', 'descuento', 'importe_total', 'metodo_pago',
       'envio_gratis', 'calificacion', 'devuelto', 'canal', 'hoja_origen',
       'categoria_producto', 'nombre_producto', 'marca', 'costo_unitario',
       'precio_lista', 'peso_kg', 'proveedor', 'stock_disponible',
       'fecha_lanzamiento', 'rating_promedio_producto', 'edad', 'estado_civil',
       'nivel_educativo', 'ingresos_anuales', 'tiene_hijos',
       'adolescentes_en_casa', 'fecha_registro', 'ciudad', 'region',
       'latitude', 'longitude', 'segmento_cliente', 'visitas_web_mes'],
      dtype='str')

In [68]:
df_final.shape

(52000, 37)

In [69]:
print("Numero de filas en df_clientes:", len(df_clientes))
print("numero de filas en df_ventas_productos es:", len(df_ventas_productos))
print("numero de filas en df_final es :", len(df_final))

Numero de filas en df_clientes: 8000
numero de filas en df_ventas_productos es: 52000
numero de filas en df_final es : 52000

In [72]:
df_final.head(3).T

,0,1,2
order_id,1,2,3
id_,7ec28fa9-cad8-4f9a-a5b4-04a3f722c107,0f14d6ee-e853-448f-a20f-d6c933956321,5db0a392-f9b6-48c4-a1b0-bdd040ab4917
product_id,P0086,P0086,P0001
fecha_pedido,3-septiembre-2022,18-noviembre-2022,14-enero-2022
cantidad,4,1,1
precio_unitario,"27,29","68,24","25,84"
descuento,0.1,0.05,0.1
importe_total,"98,23","64,83","23,26"
metodo_pago,PAYPAL,PayPal,Tarjeta de credito
envio_gratis,0,0,0
calificacion,4.0,3.0,4.0
devuelto,no,no,no
canal,App movil,Tienda fisica,App movil
hoja_origen,2022,2022,2022
categoria_producto,Libros,Libros,Electronica
nombre_producto,Manual Vantia Pro,Manual Vantia Pro,Auriculares Urbanix Basic
marca,Vantia,Vantia,Urbanix
costo_unitario,"26,68","26,68","26,73"
precio_lista,"58,69","58,69","45,70"
peso_kg,9.57,9.57,9.6
proveedor,Norte Logistica,Norte Logistica,Global Supply SL
stock_disponible,177,177,383
fecha_lanzamiento,7-marzo-2023,7-marzo-2023,31-mayo-2020
rating_promedio_producto,2.97,2.97,3.6
edad,40.0,38.0,45.0
estado_civil,Soltero,CASADO,casado
nivel_educativo,grado universitario,grado universitario,bachillerato
ingresos_anuales,33352,53296,59958
tiene_hijos,0.0,1.0,0.0
adolescentes_en_casa,0.0,0.0,0.0
fecha_registro,1-enero-2022,28-agosto-2022,24-diciembre-2022
ciudad,Valencia,Bilbao,Malaga
region,Este,Norte,Sur
latitude,40.256,40.08,41.581
longitude,-0.274,-3.699,-8.83
segmento_cliente,Nuevo,Recurrente,Nuevo
visitas_web_mes,6,10,5

In [73]:
# Comprobamos cuántos registros de la campaña son valores nulos, solo los registros con valores nulos  
nulos = df_final.isna().sum()
nulos[nulos>0].sort_values(ascending=False)

calificacion                7773
edad                        3039
nivel_educativo             2063
rating_promedio_producto    1133
tiene_hijos                 1038
metodo_pago                  780
marca                        567
estado_civil                 524
fecha_registro               253
dtype: int64

8️⃣ Guardar el dataset integrado
Guardamos el resultado de esta fase como 01_datos_integrados para poder continuar con la Fase 2 (Limpieza y transformación) sin tener que repetir la carga y el merge cada vez.

In [74]:
df_final.to_csv("01_datos_integrados.csv", index=False)