### FASE 2. Limpieza y transformación de datos

**Proyecto:** Análisis Exploratorio de Datos — Ingresos totales por ventas a clientes de un comercio.

**Objetivo de esta fase:**
Corregir errores, tratar datos incompletos y dejar el dataset preparado para el análisis exploratorio (Fase 3).

**Punto de partida:** `01_datos_integrados.csv` (52.000 filas × 37 columnas), resultado de la Fase 1.

**Flujo de limpieza que seguiremos:**
1. Importación de Librerias y Exploración inicial 
2. Corregir tipos de datos.
3. Tratar valores nulos.
4. Eliminar duplicados.
5. Limpiar datos inconsistentes.
6. Eliminar variables irrelevantes.
7. Detectar y tratar outliers.
8. Validación final y guardado del dataset limpio.

#### 1️⃣ Importacion de librerias y Exploración inicial

In [19]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)

df = pd.read_csv(r"../data/processed/01_datos_integrados.csv")
df.head(3).T

,0,1,2
order_id,1,2,3
id_,7ec28fa9-cad8-4f9a-a5b4-04a3f722c107,0f14d6ee-e853-448f-a20f-d6c933956321,5db0a392-f9b6-48c4-a1b0-bdd040ab4917
product_id,P0086,P0086,P0001
fecha_pedido,3-septiembre-2022,18-noviembre-2022,14-enero-2022
cantidad,4,1,1
precio_unitario,"27,29","68,24","25,84"
descuento,0.1,0.05,0.1
importe_total,"98,23","64,83","23,26"
metodo_pago,PAYPAL,PayPal,Tarjeta de credito
envio_gratis,0,0,0
calificacion,4.0,3.0,4.0
devuelto,no,no,no
canal,App movil,Tienda fisica,App movil
hoja_origen,2022,2022,2022
categoria_producto,Libros,Libros,Electronica
nombre_producto,Manual Vantia Pro,Manual Vantia Pro,Auriculares Urbanix Basic
marca,Vantia,Vantia,Urbanix
costo_unitario,"26,68","26,68","26,73"
precio_lista,"58,69","58,69","45,70"
peso_kg,9.57,9.57,9.6
proveedor,Norte Logistica,Norte Logistica,Global Supply SL
stock_disponible,177,177,383
fecha_lanzamiento,7-marzo-2023,7-marzo-2023,31-mayo-2020
rating_promedio_producto,2.97,2.97,3.6
edad,40.0,38.0,45.0
estado_civil,Soltero,CASADO,casado
nivel_educativo,grado universitario,grado universitario,bachillerato
ingresos_anuales,33352,53296,59958
tiene_hijos,0.0,1.0,0.0
adolescentes_en_casa,0.0,0.0,0.0
fecha_registro,1-enero-2022,28-agosto-2022,24-diciembre-2022
ciudad,Valencia,Bilbao,Malaga
region,Este,Norte,Sur
latitude,40.256,40.08,41.581
longitude,-0.274,-3.699,-8.83
segmento_cliente,Nuevo,Recurrente,Nuevo
visitas_web_mes,6,10,5

Tamaño del DataFrame

In [20]:
print(f"El archivo 01_carga_integracion tiene {df.shape[0]} filas y {df.shape[1]} columnas")

El archivo 01_carga_integracion tiene 52000 filas y 37 columnas

Informacion General

In [4]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  52000 non-null  int64
 1   id_                       52000 non-null  str
 2   product_id                52000 non-null  str
 3   fecha_pedido              52000 non-null  str
 4   cantidad                  52000 non-null  int64
 5   precio_unitario           52000 non-null  str
 6   descuento                 52000 non-null  float64
 7   importe_total             52000 non-null  str
 8   metodo_pago               51220 non-null  str
 9   envio_gratis              52000 non-null  int64
 10  calificacion              44227 non-null  float64
 11  devuelto                  52000 non-null  str
 12  canal                     52000 non-null  str
 13  hoja_origen               52000 non-null  int64
 14  categoria_producto        52000 non-null  str
 15  nombre_producto           52000 non-null  str
 16  marca                     51433 non-null  str
 17  costo_unitario            52000 non-null  str
 18  precio_lista              52000 non-null  str
 19  peso_kg                   52000 non-null  float64
 20  proveedor                 52000 non-null  str
 21  stock_disponible          52000 non-null  int64
 22  fecha_lanzamiento         52000 non-null  str
 23  rating_promedio_producto  50867 non-null  float64
 24  edad                      48961 non-null  float64
 25  estado_civil              51476 non-null  str
 26  nivel_educativo           49937 non-null  str
 27  ingresos_anuales          52000 non-null  int64
 28  tiene_hijos               50962 non-null  float64
 29  adolescentes_en_casa      52000 non-null  float64
 30  fecha_registro            51747 non-null  str
 31  ciudad                    52000 non-null  str
 32  region                    52000 non-null  str
 33  latitude                  52000 non-null  float64
 34  longitude                 52000 non-null  float64
 35  segmento_cliente          52000 non-null  str
 36  visitas_web_mes           52000 non-null  int64
dtypes: float64(9), int64(7), str(21)
memory usage: 25.2 MB

In [5]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,52000.0,NaN,NaN,NaN,26000.5,15011.251336,1.0,13000.75,26000.5,39000.25,52000.0
id_,52000,7987,f9d54acf-ff02-4eda-a470-4e10a762f16a,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_id,52000,90,P0003,678,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fecha_pedido,52000,1457,2-junio-2022,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cantidad,52000.0,NaN,NaN,NaN,2.047192,1.201054,1.0,1.0,2.0,3.0,5.0
precio_unitario,52000,12918,"32,51",18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
descuento,52000.0,NaN,NaN,NaN,0.070436,0.076881,0.0,0.0,0.05,0.1,0.3
importe_total,52000,21552,"24,24",15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metodo_pago,51220,12,tarjeta de debito,6464,NaN,NaN,NaN,NaN,NaN,NaN,NaN
envio_gratis,52000.0,NaN,NaN,NaN,0.301288,0.458822,0.0,0.0,0.0,1.0,1.0
calificacion,44227.0,NaN,NaN,NaN,4.052502,1.048372,1.0,4.0,4.0,5.0,5.0
devuelto,52000,4,NO,24633,NaN,NaN,NaN,NaN,NaN,NaN,NaN
canal,52000,4,Web,20887,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hoja_origen,52000.0,NaN,NaN,NaN,2023.5,1.118045,2022.0,2022.75,2023.5,2024.25,2025.0
categoria_producto,52000,5,Electronica,10596,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nombre_producto,52000,90,Auriculares Nova Max,678,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marca,51433,8,Vantia,10898,NaN,NaN,NaN,NaN,NaN,NaN,NaN
costo_unitario,52000,88,"18,35",1140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
precio_lista,52000,90,"98,89",678,NaN,NaN,NaN,NaN,NaN,NaN,NaN
peso_kg,52000.0,NaN,NaN,NaN,6.216765,3.513158,0.3,2.95,6.89,9.28,11.98
proveedor,52000,4,Norte Logistica,15098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stock_disponible,52000.0,NaN,NaN,NaN,250.003231,134.013918,5.0,148.0,263.0,368.0,488.0
fecha_lanzamiento,52000,88,6-marzo-2021,1217,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rating_promedio_producto,50867.0,NaN,NaN,NaN,3.876116,0.682173,2.63,3.33,3.86,4.45,5.0
edad,48961.0,NaN,NaN,NaN,40.153551,12.517461,18.0,31.0,40.0,48.0,85.0
estado_civil,51476,9,CASADO,8724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nivel_educativo,49937,5,grado universitario,17482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ingresos_anuales,52000.0,NaN,NaN,NaN,43879.338481,16106.532838,14057.0,32112.0,41124.0,52973.0,149422.0
tiene_hijos,50962.0,NaN,NaN,NaN,0.447373,0.497228,0.0,0.0,0.0,1.0,1.0
adolescentes_en_casa,52000.0,NaN,NaN,NaN,0.306096,0.460875,0.0,0.0,0.0,1.0,1.0
fecha_registro,51747,1802,7-marzo-2019,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ciudad,52000,10,Malaga,5550,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,52000,4,Sur,21229,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,52000.0,NaN,NaN,NaN,39.7692,2.15054,36.001,37.93,39.791,41.6,43.499
longitude,52000.0,NaN,NaN,NaN,-2.845237,3.527497,-8.999,-5.857,-2.826,0.167,3.299
segmento_cliente,52000,4,Recurrente,20768,NaN,NaN,NaN,NaN,NaN,NaN,NaN
visitas_web_mes,52000.0,NaN,NaN,NaN,8.027096,2.813336,0.0,6.0,8.0,10.0,21.0

In [6]:
df.describe(include='string').T

                    count unique                                   top   freq
id_                 52000   7987  f9d54acf-ff02-4eda-a470-4e10a762f16a     20
product_id          52000     90                                 P0003    678
fecha_pedido        52000   1457                          2-junio-2022     57
precio_unitario     52000  12918                                 32,51     18
importe_total       52000  21552                                 24,24     15
metodo_pago         51220     12                     tarjeta de debito   6464
devuelto            52000      4                                    NO  24633
canal               52000      4                                   Web  20887
categoria_producto  52000      5                           Electronica  10596
nombre_producto     52000     90                  Auriculares Nova Max    678
marca               51433      8                                Vantia  10898
costo_unitario      52000     88                                 18,35   1140
precio_lista        52000     90                                 98,89    678
proveedor           52000      4                       Norte Logistica  15098
fecha_lanzamiento   52000     88                          6-marzo-2021   1217
estado_civil        51476      9                                CASADO   8724
nivel_educativo     49937      5                   grado universitario  17482
fecha_registro      51747   1802                          7-marzo-2019     87
ciudad              52000     10                                Malaga   5550
region              52000      4                                   Sur  21229
segmento_cliente    52000      4                            Recurrente  20768

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
order_id,52000.0,26000.500000,15011.251336,1.000,13000.750,26000.500,39000.250,52000.000
cantidad,52000.0,2.047192,1.201054,1.000,1.000,2.000,3.000,5.000
descuento,52000.0,0.070436,0.076881,0.000,0.000,0.050,0.100,0.300
envio_gratis,52000.0,0.301288,0.458822,0.000,0.000,0.000,1.000,1.000
calificacion,44227.0,4.052502,1.048372,1.000,4.000,4.000,5.000,5.000
hoja_origen,52000.0,2023.500000,1.118045,2022.000,2022.750,2023.500,2024.250,2025.000
peso_kg,52000.0,6.216765,3.513158,0.300,2.950,6.890,9.280,11.980
stock_disponible,52000.0,250.003231,134.013918,5.000,148.000,263.000,368.000,488.000
rating_promedio_producto,50867.0,3.876116,0.682173,2.630,3.330,3.860,4.450,5.000
edad,48961.0,40.153551,12.517461,18.000,31.000,40.000,48.000,85.000
ingresos_anuales,52000.0,43879.338481,16106.532838,14057.000,32112.000,41124.000,52973.000,149422.000
tiene_hijos,50962.0,0.447373,0.497228,0.000,0.000,0.000,1.000,1.000
adolescentes_en_casa,52000.0,0.306096,0.460875,0.000,0.000,0.000,1.000,1.000
latitude,52000.0,39.769200,2.150540,36.001,37.930,39.791,41.600,43.499
longitude,52000.0,-2.845237,3.527497,-8.999,-5.857,-2.826,0.167,3.299
visitas_web_mes,52000.0,8.027096,2.813336,0.000,6.000,8.000,10.000,21.000

Valores unicos

In [21]:
df.nunique()

order_id                    52000
id_                          7987
product_id                     90
fecha_pedido                 1457
cantidad                        5
precio_unitario             12918
descuento                       6
importe_total               21552
metodo_pago                    12
envio_gratis                    2
calificacion                    5
devuelto                        4
canal                           4
hoja_origen                     4
categoria_producto              5
nombre_producto                90
marca                           8
costo_unitario                 88
precio_lista                   90
peso_kg                        89
proveedor                       4
stock_disponible               84
fecha_lanzamiento              88
rating_promedio_producto       75
edad                           67
estado_civil                    9
nivel_educativo                 5
ingresos_anuales             7414
tiene_hijos                     2
adolescentes_en_casa            2
fecha_registro               1802
ciudad                         10
region                          4
latitude                     4910
longitude                    5851
segmento_cliente                4
visitas_web_mes                22
dtype: int64

In [22]:
valores = pd.DataFrame({
    'nunique': df.nunique(),
    'dtype': df.dtypes,
})

valores

                          nunique    dtype
order_id                    52000    int64
id_                          7987      str
product_id                     90      str
fecha_pedido                 1457      str
cantidad                        5    int64
precio_unitario             12918      str
descuento                       6  float64
importe_total               21552      str
metodo_pago                    12      str
envio_gratis                    2    int64
calificacion                    5  float64
devuelto                        4      str
canal                           4      str
hoja_origen                     4    int64
categoria_producto              5      str
nombre_producto                90      str
marca                           8      str
costo_unitario                 88      str
precio_lista                   90      str
peso_kg                        89  float64
proveedor                       4      str
stock_disponible               84    int64
fecha_lanzamiento              88      str
rating_promedio_producto       75  float64
edad                           67  float64
estado_civil                    9      str
nivel_educativo                 5      str
ingresos_anuales             7414    int64
tiene_hijos                     2  float64
adolescentes_en_casa            2  float64
fecha_registro               1802      str
ciudad                         10      str
region                          4      str
latitude                     4910  float64
longitude                    5851  float64
segmento_cliente                4      str
visitas_web_mes                22    int64

#### 2️⃣ Corregir tipos de datos

Corregimos los tipos **antes** de tratar los nulos, ya que muchas columnas numéricas están almacenadas como texto y esto afectaría al cálculo de medias/medianas para la imputación. 

Nota: esta información está recogida en la Fase 1 Observaciones Inciales que unificaremos aqui.

Verificador de procesos

In [32]:
datos = pd.DataFrame({
    'nunique': df.nunique(),
    'dtype': df.dtypes,
    'ejemplos': df.apply(lambda x: "   ".join(map(str, x.sample(2))))
})

datos

,nunique,dtype,ejemplos
order_id,52000,int64,41277 5322
id_,7987,str,22271a52-ef19-4522-a353-6b91853fde55 81368d7...
product_id,90,str,P0020 P0011
fecha_pedido,1457,datetime64[us],2025-03-21 00:00:00 2023-04-28 00:00:00
cantidad,5,int64,1 1
precio_unitario,12918,float64,44.36 28.71
descuento,6,float64,0.05 0.0
importe_total,21552,float64,32.0 34.28
metodo_pago,12,str,tarjeta de debito tarjeta de debito
envio_gratis,2,int64,0 1
calificacion,5,float64,5.0 1.0
devuelto,4,str,NO NO
canal,4,str,Tienda fisica Web
hoja_origen,4,int64,2024 2024
categoria_producto,5,str,Electronica Deporte
nombre_producto,90,str,Bicicleta Zentra Max Casco Norte&Co Max
marca,8,str,Urbanix Vantia
costo_unitario,88,float64,16.12 34.23
precio_lista,90,float64,25.2 17.78
peso_kg,89,float64,7.45 0.92
proveedor,4,str,Global Supply SL Comercial Atlas
stock_disponible,84,int64,263 214
fecha_lanzamiento,88,datetime64[us],2021-03-06 00:00:00 2023-02-18 00:00:00
rating_promedio_producto,75,float64,3.25 2.63
edad,67,float64,45.0 43.0
estado_civil,9,str,SOLTERO soltero
nivel_educativo,5,str,bachillerato grado universitario
ingresos_anuales,7414,int64,34096 31637
tiene_hijos,2,float64,nan 0.0
adolescentes_en_casa,2,float64,0.0 1.0
fecha_registro,1802,datetime64[us],2018-03-28 00:00:00 2020-02-23 00:00:00
ciudad,10,str,Sevilla Valencia
region,4,str,Este Norte
latitude,4910,float64,38.637 37.469
longitude,5851,float64,1.779 0.175
segmento_cliente,4,str,Nuevo Nuevo
visitas_web_mes,22,int64,8 6

**Observaciones iniciales de `df_clientes`:**

- Hay columnas con valores nulos (`edad`, `estado_civil`, `nivel_educativo`, `tiene_hijos`, `fecha_registro`),se tratarán en la **Fase 2 (Limpieza)**.
- Las columnas (`tiene_hijos`, `adolescentes_en_casa`) en una primera visual parecen variables binarias, se tratarán en la **Fase 2 (Limpieza)**.


**Observaciones iniciales de `df_productos`:**

- Hay dos columna con valores nulos (`rating_promedio_producto`, `marca`),se tratarán en la **Fase 2 (Limpieza)**.



*Observaciones iniciales de `df_ventas`:**


- Hay dos columnas con valores nulos (`metodo_pago`,`calificacion` ),se tratarán en la **Fase 2**.

- La columna (`envio_gratis`) en una primera visual parece una variable binaria, se tratarán en la **Fase 2**.

2.1. Columnas `fecha_registro, fecha_lanzamiento ,fecha_pedido` (texto con mes en español → datetime)

In [24]:
df[['fecha_registro','fecha_lanzamiento','fecha_pedido']].dtypes

fecha_registro       str
fecha_lanzamiento    str
fecha_pedido         str
dtype: object

In [25]:
df[['fecha_registro','fecha_lanzamiento','fecha_pedido']].sample(3)

         fecha_registro  fecha_lanzamiento        fecha_pedido
36659  6-noviembre-2019      19-abril-2019        6-enero-2024
11998     14-junio-2020  31-diciembre-2023      2-octubre-2022
6925      18-marzo-2020       6-abril-2024  12-septiembre-2022

Comvertimos columnas a datetime

In [26]:
meses = {
    "enero": "01",
    "febrero": "02",
    "marzo": "03",
    "abril": "04",
    "mayo": "05",
    "junio": "06",
    "julio": "07",
    "agosto": "08",
    "septiembre": "09",
    "octubre": "10",
    "noviembre": "11",
    "diciembre": "12",
}

# Reemplazar los nombres de los meses
fechas =['fecha_registro','fecha_lanzamiento','fecha_pedido']

df[fechas] = df[fechas].replace(meses, regex=True)


# Convertir a datetime
for col in fechas: 
    df[col] = pd.to_datetime(df[col], format="%d-%m-%Y", errors="coerce")

df[fechas].sample(3)

      fecha_registro fecha_lanzamiento fecha_pedido
50558     2018-06-30        2020-12-12   2025-12-01
23706     2021-11-09        2021-09-23   2023-12-05
42896     2022-05-19        2023-10-27   2025-04-10

In [27]:
df[fechas].dtypes

fecha_registro       datetime64[us]
fecha_lanzamiento    datetime64[us]
fecha_pedido         datetime64[us]
dtype: object

**Observaciones**
- Las columnas `fecha_registro, fecha_lanzamiento , fecha_pedido` han sido primero modificado el texto a numero y despues convertidas a datetime.

2.2. Columnas económicas de string → float, y reemplazar "," por "."

In [28]:
df[["costo_unitario", "precio_lista", "precio_unitario", "importe_total"]].dtypes

costo_unitario     str
precio_lista       str
precio_unitario    str
importe_total      str
dtype: object

In [29]:
numeros = ["costo_unitario", "precio_lista", "precio_unitario", "importe_total"]

for col in numeros:
    df[col] = df[col].astype(str).str.replace(",", ".", regex=False)
    df[col] = pd.to_numeric(df[col], errors="coerce").astype(float)

df[numeros].dtypes

costo_unitario     float64
precio_lista       float64
precio_unitario    float64
importe_total      float64
dtype: object

In [30]:
df[["costo_unitario", "precio_lista", "precio_unitario", "importe_total"]].nunique()

costo_unitario        88
precio_lista          90
precio_unitario    12918
importe_total      21552
dtype: int64

**Observaciones**
- Las columnas `"costo_unitario", "precio_lista", "precio_unitario", "importe_total"` se ha reemplazar la "," por el "." para poder pasar los valores de string a float.

2.3. Columnas con mayusculas y espacios a minusculas (unificar todos los datos)

In [58]:
val_unicos = pd.DataFrame({
    col: pd.Series(df[col].unique())
    for col in df.select_dtypes(include=["object", "string"]).columns
    if col not in ["id_","product_id","nombre_producto"]
})

val_unicos

,metodo_pago,devuelto,canal,categoria_producto,marca,proveedor,estado_civil,nivel_educativo,ciudad,region,segmento_cliente
0,paypal,no,app movil,libros,vantia,norte logistica,soltero,grado universitario,valencia,este,nuevo
1,tarjeta de credito,si,tienda fisica,electronica,urbanix,global supply sl,casado,bachillerato,bilbao,norte,recurrente
2,contrareembolso,NaN,marketplace,deporte,kore,distribuidora iberia,NaN,basico,malaga,sur,corporativo
3,tarjeta de debito,NaN,web,hogar,nova,comercial atlas,divorciado,master,vigo,centro,vip
4,transferencia,NaN,NaN,ropa,norte&co,NaN,NaN,doctorado,sevilla,NaN,NaN
5,NaN,NaN,NaN,NaN,prisma,NaN,NaN,NaN,madrid,NaN,NaN
6,NaN,NaN,NaN,NaN,zentra,NaN,NaN,NaN,barcelona,NaN,NaN
7,NaN,NaN,NaN,NaN,lumen,NaN,NaN,NaN,murcia,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,granada,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zaragoza,NaN,NaN

In [40]:
cols = [
    "metodo_pago", "devuelto", "canal", "categoria_producto",
    "marca", "proveedor", "estado_civil",
    "nivel_educativo", "ciudad", "region", "segmento_cliente"
]

df[cols] = df[cols].apply(lambda x: x.str.strip().str.lower())

In [59]:
df["nombre_producto"].dropna().sort_values().unique()

<ArrowStringArray>
[  'Aspiradora Norte&Co Max',   'Aspiradora Vantia Basic',
     'Aspiradora Vantia Pro',      'Auriculares Nova Max',
 'Auriculares Urbanix Basic',   'Auriculares Urbanix Pro',
            'Balon Kore Max',        'Balon Vantia Basic',
          'Balon Zentra Pro',      'Bicicleta Kore Basic',
        'Bicicleta Kore Pro',      'Bicicleta Zentra Max',
        'Biografia Kore Pro',        'Biografia Nova Max',
    'Biografia Zentra Basic',   'Cafetera Norte&Co Basic',
         'Cafetera Nova Pro',       'Cafetera Zentra Max',
           'Camara Kore Max',          'Camara Lumen Pro',
     'Camara Norte&Co Basic',     'Camiseta Prisma Basic',
       'Camiseta Vantia Max',       'Camiseta Vantia Pro',
           'Casco Lumen Pro',        'Casco Norte&Co Max',
        'Casco Vantia Basic',       'Chaqueta Kore Basic',
     'Chaqueta Norte&Co Max',       'Chaqueta Zentra Pro',
            'Comic Kore Max',        'Comic Norte&Co Pro',
        'Comic Prisma Basic',       'Ensayo Norte&Co Max',
         'Ensayo Prisma Pro',      'Ensayo Urbanix Basic',
   'Estanteria Norte&Co Max',     'Estanteria Nova Basic',
     'Estanteria Vantia Pro',      'Esterilla Vantia Max',
    'Esterilla Zentra Basic',      'Esterilla Zentra Pro',
          'Gorra Kore Basic',           'Gorra Lumen Max',
            'Gorra Nova Pro',          'Lampara Nova Pro',
      'Lampara Vantia Basic',        'Lampara Vantia Max',
       'Mancuernas Nova Pro',   'Mancuernas Vantia Basic',
     'Mancuernas Vantia Max',         'Manual Vantia Pro',
       'Manual Zentra Basic',         'Manual Zentra Max',
        'Novela Lumen Basic',        'Novela Urbanix Max',
         'Novela Vantia Pro',     'Pantalon Norte&Co Max',
     'Pantalon Norte&Co Pro',     'Pantalon Prisma Basic',
        'Poesia Lumen Basic',         'Poesia Prisma Pro',
         'Poesia Vantia Max',       'Portatil Kore Basic',
         'Portatil Kore Max',      'Portatil Urbanix Pro',
        'Raqueta Prisma Max',      'Raqueta Vantia Basic',
        'Raqueta Vantia Pro',         'Sarten Kore Basic',
        'Sarten Urbanix Max',         'Sarten Zentra Pro',
        'Silla Norte&Co Pro',            'Silla Nova Max',
        'Silla Vantia Basic', 'Smartphone Norte&Co Basic',
     'Smartphone Zentra Max',     'Smartphone Zentra Pro',
   'Smartwatch Prisma Basic',    'Smartwatch Urbanix Max',
     'Smartwatch Vantia Pro',        'Tablet Lumen Basic',
           'Tablet Nova Max',         'Tablet Prisma Pro',
         'Vestido Lumen Pro',    'Vestido Norte&Co Basic',
        'Vestido Prisma Max',    'Zapatillas Lumen Basic',
       'Zapatillas Nova Pro',     'Zapatillas Prisma Max']
Length: 90, dtype: str

In [60]:
val_unicos_mod = pd.DataFrame({
    col: pd.Series(df[col].unique())
    for col in df.select_dtypes(include=["object", "string"]).columns
    if col not in ["id_","product_id","nombre_producto"]
})

val_unicos_mod

,metodo_pago,devuelto,canal,categoria_producto,marca,proveedor,estado_civil,nivel_educativo,ciudad,region,segmento_cliente
0,paypal,no,app movil,libros,vantia,norte logistica,soltero,grado universitario,valencia,este,nuevo
1,tarjeta de credito,si,tienda fisica,electronica,urbanix,global supply sl,casado,bachillerato,bilbao,norte,recurrente
2,contrareembolso,NaN,marketplace,deporte,kore,distribuidora iberia,NaN,basico,malaga,sur,corporativo
3,tarjeta de debito,NaN,web,hogar,nova,comercial atlas,divorciado,master,vigo,centro,vip
4,transferencia,NaN,NaN,ropa,norte&co,NaN,NaN,doctorado,sevilla,NaN,NaN
5,NaN,NaN,NaN,NaN,prisma,NaN,NaN,NaN,madrid,NaN,NaN
6,NaN,NaN,NaN,NaN,zentra,NaN,NaN,NaN,barcelona,NaN,NaN
7,NaN,NaN,NaN,NaN,lumen,NaN,NaN,NaN,murcia,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,granada,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zaragoza,NaN,NaN

2.5. Columnas binarias `envio_gratis`, `tiene_hijos`, `adolescentes_en_casa` → texto legible

Estas columnas son categóricas (Sí/No) aunque estén almacenadas como 0.0/1.0. Las convertimos a texto (`"si"` / `"no"`) para que sean coherentes  y más claras en los gráficos de la Fase 3. Los nulos se mantienen de momento (se tratarán en el siguiente paso).

In [91]:
df[["envio_gratis", "tiene_hijos", "adolescentes_en_casa"]].nunique()

envio_gratis            2
tiene_hijos             2
adolescentes_en_casa    2
dtype: int64

In [94]:
df[["envio_gratis", "tiene_hijos", "adolescentes_en_casa"]].apply(lambda c: c.value_counts(dropna=False))

     envio_gratis  tiene_hijos  adolescentes_en_casa
0.0       36333.0        28163               36083.0
1.0       15667.0        22799               15917.0
NaN           NaN         1038                   NaN

In [95]:
for col in ["envio_gratis", "tiene_hijos", "adolescentes_en_casa"]:
    df[col] = df[col].replace({1.0: "si", 0.0: "no"}).astype("str")

In [96]:
df[["envio_gratis", "tiene_hijos", "adolescentes_en_casa"]].apply(lambda c: c.value_counts(dropna=False))

     envio_gratis  tiene_hijos  adolescentes_en_casa
no        36333.0        28163               36083.0
si        15667.0        22799               15917.0
NaN           NaN         1038                   NaN

In [100]:
val_unicos_mod = pd.DataFrame({
    col: pd.Series(df[col].unique())
    for col in df.select_dtypes(include=["object", "string"]).columns
    if col not in ["id_","product_id","nombre_producto"]
})

val_unicos_mod

,metodo_pago,envio_gratis,devuelto,canal,categoria_producto,marca,proveedor,estado_civil,nivel_educativo,tiene_hijos,adolescentes_en_casa,ciudad,region,segmento_cliente
0,paypal,no,no,app movil,libros,vantia,norte logistica,soltero,grado universitario,no,no,valencia,este,nuevo
1,tarjeta de credito,si,si,tienda fisica,electronica,urbanix,global supply sl,casado,bachillerato,si,si,bilbao,norte,recurrente
2,contrareembolso,NaN,NaN,marketplace,deporte,kore,distribuidora iberia,NaN,basico,NaN,NaN,malaga,sur,corporativo
3,tarjeta de debito,NaN,NaN,web,hogar,nova,comercial atlas,divorciado,master,NaN,NaN,vigo,centro,vip
4,transferencia,NaN,NaN,NaN,ropa,norte&co,NaN,NaN,doctorado,NaN,NaN,sevilla,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,prisma,NaN,NaN,NaN,NaN,NaN,madrid,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,zentra,NaN,NaN,NaN,NaN,NaN,barcelona,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,lumen,NaN,NaN,NaN,NaN,NaN,murcia,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,granada,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zaragoza,NaN,NaN